package com.flaringapp.ligretto.core.designsystem

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

fun appLightColorScheme() = ColorScheme(
    primary = AppColorPalette.primary40,
    onPrimary = AppColorPalette.primary100,
    primaryContainer = AppColorPalette.primary90,
    onPrimaryContainer = AppColorPalette.primary10,
    inversePrimary = AppColorPalette.primary10,
    secondary = AppColorPalette.secondary40,
    onSecondary = AppColorPalette.secondary100,
    secondaryContainer = AppColorPalette.secondary90,
    onSecondaryContainer = AppColorPalette.secondary10,
    tertiary = AppColorPalette.tertiary40,
    onTertiary = AppColorPalette.tertiary100,
    tertiaryContainer = AppColorPalette.tertiary90,
    onTertiaryContainer = AppColorPalette.tertiary10,
    background = Color(0xFFFFF8F6),
    onBackground = AppColorPalette.neutral10,
    surface = Color(0xFFFFF8F6),
    onSurface = AppColorPalette.neutral10,
    surfaceVariant = AppColorPalette.neutralVariant90,
    onSurfaceVariant = AppColorPalette.neutralVariant30,
    surfaceTint = AppColorPalette.primary40,
    inverseSurface = AppColorPalette.neutral10,
    inverseOnSurface = AppColorPalette.neutral99,
    error = AppColorPalette.error40,
    onError = AppColorPalette.error100,
    errorContainer = AppColorPalette.error90,
    onErrorContainer = AppColorPalette.error10,
    outline = AppColorPalette.neutralVariant50,
    outlineVariant = AppColorPalette.neutral50,
    scrim = Color.Black,
    surfaceBright = Color(0xFFFFF8F6),
    surfaceDim = Color(0xFFE4D7D4),
    surfaceContainer = Color(0xFFF8EBE8),
    surfaceContainerHigh = Color(0xFFF3E5E2),
    surfaceContainerHighest = Color(0xFFEDE0DC),
    surfaceContainerLow = Color(0xFFFEF1ED),
    surfaceContainerLowest = Color(0xFFFFFBFF),
)

fun appDarkColorScheme() = ColorScheme(
    primary = AppColorPalette.primary80,
    onPrimary = AppColorPalette.primary20,
    primaryContainer = AppColorPalette.primary30,
    onPrimaryContainer = AppColorPalette.primary90,
    inversePrimary = AppColorPalette.primary90,
    secondary = AppColorPalette.secondary80,
    onSecondary = AppColorPalette.secondary20,
    secondaryContainer = AppColorPalette.secondary30,
    onSecondaryContainer = AppColorPalette.secondary90,
    tertiary = AppColorPalette.tertiary80,
    onTertiary = AppColorPalette.tertiary20,
    tertiaryContainer = AppColorPalette.tertiary30,
    onTertiaryContainer = AppColorPalette.tertiary90,
    background = Color(0xFF181210),
    onBackground = AppColorPalette.neutral90,
    surface = Color(0xFF181210),
    onSurface = AppColorPalette.neutral80,
    surfaceVariant = AppColorPalette.neutralVariant30,
    onSurfaceVariant = AppColorPalette.neutralVariant80,
    surfaceTint = AppColorPalette.primary80,
    inverseSurface = AppColorPalette.neutral80,
    inverseOnSurface = AppColorPalette.neutral10,
    error = AppColorPalette.error80,
    onError = AppColorPalette.error20,
    errorContainer = AppColorPalette.error30,
    onErrorContainer = AppColorPalette.error90,
    outline = AppColorPalette.neutralVariant60,
    outlineVariant = AppColorPalette.neutral60,
    scrim = Color.Black,
    surfaceBright = Color(0xFF3F3835),
    surfaceDim = Color(0xFF181210),
    surfaceContainer = Color(0xFF251E1C),
    surfaceContainerHigh = Color(0xFF2F2826),
    surfaceContainerHighest = Color(0xFF3B3331),
    surfaceContainerLow = Color(0xFF201A18),
    surfaceContainerLowest = Color(0xFF120D0B),
)
